use ruby or yq for the YAML check
yq is present in the ubuntu-latest GH Action runner
ruby is on our openSUSE machines

diff --git a/products.d/Makefile b/products.d/Makefile
--- a/products.d/Makefile
+++ b/products.d/Makefile
@@ -3,4 +3,14 @@
 
 .PHONY: check
 check:
-	ruby -ryaml -e 'Dir.glob("*.{yml,yaml}").sort.each { |fn| puts fn; YAML.safe_load(File.read(fn)) }; puts "OK"'
+	set -eu; \
+	if type ruby >/dev/null 2>&1; then \
+	  echo "Checking YAML files with ruby"; \
+	  ruby -ryaml -e 'Dir.glob("*.yaml").sort.each { |fn| puts fn; YAML.safe_load(File.read(fn)) }; puts "OK"'; \
+	elif type yq >/dev/null 2>&1; then \
+	  echo "Checking YAML files with yq"; \
+	  for P in *.yaml; do yq eval $$P >/dev/null; done; echo OK; \
+	else \
+	  echo "Error: cannot check YAML files; install either ruby or yq."; \
+	  exit 1 ; \
+	fi
